sonar.projectKey=bysurehrms_hrms
sonar.projectName=hrms

sonar.sources=app,config,routes,database
sonar.tests=tests

sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,public/build/**,node_modules/**
